baseURL = 'https://chinese-anime.pages.dev'
languageCode = 'en-us'
title = 'Chinese Anime'
theme = 'anime'
enableRobotsTXT = 'true'
paginate = 18

[params]
  Description = 'Donghua english sub, Lucifer donghua, Chinese anime english sub, Watch donghua online eng sub, Donghua sub english, Watch donghua english sub, Donghua online eng sub, Chinese anime with english subtitles, Donghua anime eng sub, Watch chinese anime eng sub, Chineseanime, Chinese anime watch online, Chinese anime english subtitles.'
  favicon = 'https://i3.wp.com/www.chineseanime.co.in/wp-content/uploads/2021/09/cropped-4865770.jpg'
  twitter = 'Rizqy'
[markup.goldmark.renderer]
 unsafe = true
[taxonomies]
  genre = 'genre'
[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "genre"
    weight = 100
  [[related.indices]]
    name = "title"
    weight = 90
  [[related.indices]]
    name = "type"
    weight = 90